### ISSUE TITLE
Add David Dotson as team member

### ISSUE THREAD

**Issue by kain88-de** [conda-forge/datreant-feedstock#2]
@conda-forge/core Could you please add @dotsdl to the team for this repository

**Comment by jakirkham** [comment]
So this hasn't happened yet only because our team update script is having issues. There is a proposed fix in the pipeline that merely needs a review and merge.

xref: https://github.com/conda-forge/conda-forge.github.io/pull/280

**Comment by dotsdl** [comment]
Should be done now I think.

**Comment by jakirkham** [comment]
Yep, looks like it.
